import { AchievementsState } from "./storage";

export type AchievementCategory =
  | "general"
  | "time"
  | "diversity"
  | "albums"
  | "playlists"
  | "likes"
  | "genres"
  | "new"
  | "old"
  | "long"
  | "short"
  | "marathon"
  | "tod"
  | "days"
  | "specific_genres";

export type AchievementRarity = "common" | "uncommon" | "rare" | "epic" | "legendary";

export interface AchievementDefinition {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  xp: number;
  isSecret: boolean;
  secretDescription?: string;
  maxProgress: number;
  check: (stats: AchievementsState["stats"]) => number;
}

const countGenreMatches = (genreCounts: { [genre: string]: number }, keywords: string[]): number => {
  let count = 0;
  for (const [genre, value] of Object.entries(genreCounts)) {
    const lower = genre.toLowerCase();
    if (keywords.some((kw) => lower.includes(kw))) {
      count += value;
    }
  }
  return count;
};

export const ACHIEVEMENT_DEFS: AchievementDefinition[] = [

  {
    id: "g1",
    name: "Premier Pas",
    description: "Écouter une chanson.",
    category: "general",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 1,
    check: (s) => s.totalSongsPlayed,
  },
  {
    id: "g2",
    name: "Centenaire",
    description: "Écouter 100 chansons.",
    category: "general",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.totalSongsPlayed,
  },
  {
    id: "g3",
    name: "Mélomane",
    description: "Écouter 500 chansons.",
    category: "general",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 500,
    check: (s) => s.totalSongsPlayed,
  },
  {
    id: "g4",
    name: "Passionné",
    description: "Écouter 1 000 chansons.",
    category: "general",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 1000,
    check: (s) => s.totalSongsPlayed,
  },
  {
    id: "g5",
    name: "Légende de la Musique",
    description: "Écouter 10 000 chansons.",
    category: "general",
    rarity: "legendary",
    xp: 1000,
    isSecret: false,
    maxProgress: 10000,
    check: (s) => s.totalSongsPlayed,
  },

  {
    id: "t1",
    name: "Auditeur Initié",
    description: "Écouter 1 heure de musique.",
    category: "time",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 1,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },
  {
    id: "t2",
    name: "Grand Voyageur",
    description: "Écouter 10 heures de musique.",
    category: "time",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 10,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },
  {
    id: "t3",
    name: "Habitué",
    description: "Écouter 100 heures de musique.",
    category: "time",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 100,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },
  {
    id: "t4",
    name: "Mélophile",
    description: "Écouter 500 heures de musique.",
    category: "time",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 500,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },
  {
    id: "t5",
    name: "Vénérable",
    description: "Écouter 1 000 heures de musique.",
    category: "time",
    rarity: "legendary",
    xp: 1000,
    isSecret: false,
    maxProgress: 1000,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },
  {
    id: "t6",
    name: "Divinité d'écoute",
    description: "Écouter 5 000 heures de musique.",
    category: "time",
    rarity: "legendary",
    xp: 1000,
    isSecret: false,
    maxProgress: 5000,
    check: (s) => Math.floor(s.totalListeningTimeMs / 3600000),
  },

  {
    id: "d1",
    name: "Explorateur Débutant",
    description: "Écouter 10 artistes différents.",
    category: "diversity",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 10,
    check: (s) => s.uniqueArtists.length,
  },
  {
    id: "d2",
    name: "Chasseur de Talents",
    description: "Écouter 100 artistes différents.",
    category: "diversity",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.uniqueArtists.length,
  },
  {
    id: "d3",
    name: "Cartographe Musical",
    description: "Écouter 500 artistes différents.",
    category: "diversity",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 500,
    check: (s) => s.uniqueArtists.length,
  },
  {
    id: "d4",
    name: "Encyclopédie Vivante",
    description: "Écouter 1 000 artistes différents.",
    category: "diversity",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 1000,
    check: (s) => s.uniqueArtists.length,
  },

  {
    id: "al1",
    name: "Premier Tour",
    description: "Finir d'écouter 1 album.",
    category: "albums",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 1,
    check: (s) => s.uniqueAlbums.length,
  },
  {
    id: "al2",
    name: "Collectionneur",
    description: "Finir d'écouter 10 albums.",
    category: "albums",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 10,
    check: (s) => s.uniqueAlbums.length,
  },
  {
    id: "al3",
    name: "Archiviste",
    description: "Finir d'écouter 50 albums.",
    category: "albums",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 50,
    check: (s) => s.uniqueAlbums.length,
  },
  {
    id: "al4",
    name: "Conservateur de Musée",
    description: "Finir d'écouter 100 albums.",
    category: "albums",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.uniqueAlbums.length,
  },

  {
    id: "p1",
    name: "Créateur en Herbe",
    description: "Créer 1 playlist.",
    category: "playlists",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 1,
    check: (s) => s.playlistsCreated,
  },
  {
    id: "p2",
    name: "Directeur Artistique",
    description: "Créer 10 playlists.",
    category: "playlists",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 10,
    check: (s) => s.playlistsCreated,
  },
  {
    id: "p3",
    name: "Magnat de la Playlist",
    description: "Créer 50 playlists.",
    category: "playlists",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 50,
    check: (s) => s.playlistsCreated,
  },

  {
    id: "lk1",
    name: "Coup de Cœur",
    description: "Ajouter 100 morceaux à vos Titres Likés.",
    category: "likes",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.playlistsAdded,
  },
  {
    id: "lk2",
    name: "Collection d'Or",
    description: "Ajouter 500 morceaux à vos Titres Likés.",
    category: "likes",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 500,
    check: (s) => s.playlistsAdded,
  },
  {
    id: "lk3",
    name: "Bibliothèque Royale",
    description: "Ajouter 1 000 morceaux à vos Titres Likés.",
    category: "likes",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 1000,
    check: (s) => s.playlistsAdded,
  },

  {
    id: "gn1",
    name: "Ouverture d'Esprit",
    description: "Découvrir 10 genres musicaux.",
    category: "genres",
    rarity: "common",
    xp: 50,
    isSecret: false,
    maxProgress: 10,
    check: (s) => s.uniqueGenres.length,
  },
  {
    id: "gn2",
    name: "Polyglotte Musical",
    description: "Découvrir 20 genres musicaux.",
    category: "genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => s.uniqueGenres.length,
  },
  {
    id: "gn3",
    name: "Caméléon",
    description: "Découvrir 50 genres musicaux.",
    category: "genres",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 50,
    check: (s) => s.uniqueGenres.length,
  },
  {
    id: "gn4",
    name: "Universel",
    description: "Découvrir 100 genres musicaux.",
    category: "genres",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.uniqueGenres.length,
  },

  {
    id: "n1",
    name: "Tête Chercheuse",
    description: "Écouter 100 nouvelles chansons.",
    category: "new",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.newSongsListened.length,
  },
  {
    id: "n2",
    name: "Pionnier",
    description: "Écouter 500 nouvelles chansons.",
    category: "new",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 500,
    check: (s) => s.newSongsListened.length,
  },

  {
    id: "o1",
    name: "Archéologue",
    description: "Écouter 100 chansons sorties avant 1990.",
    category: "old",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.oldSongsListened.length,
  },

  {
    id: "lg1",
    name: "Marathonien",
    description: "Écouter 50 morceaux de plus de 8 minutes.",
    category: "long",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 50,
    check: (s) => s.longSongsListened.length,
  },

  {
    id: "sh1",
    name: "Snack Musical",
    description: "Écouter 100 morceaux de moins de 2 minutes.",
    category: "short",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.shortSongsListened.length,
  },

  {
    id: "m1",
    name: "Infatigable",
    description: "Écouter 5 heures de musique sans pause.",
    category: "marathon",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 5,
    check: (s) => Math.floor(s.playlistsDeleted / 3600),
  },
  {
    id: "m2",
    name: "Survivant",
    description: "Écouter 10 heures de musique sans pause.",
    category: "marathon",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 10,
    check: (s) => Math.floor(s.playlistsDeleted / 3600),
  },

  {
    id: "tod1",
    name: "Insomniaque",
    description: "Écouter de la musique à minuit (entre 00h00 et 00h59).",
    category: "tod",
    rarity: "uncommon",
    xp: 100,
    isSecret: true,
    secretDescription: "Écouter de la musique au milieu de la nuit.",
    maxProgress: 1,
    check: (s) => (s.genreCounts["_tod_midnight"] || 0) >= 1 ? 1 : 0,
  },
  {
    id: "tod2",
    name: "Créature de la Nuit",
    description: "Écouter de la musique à 3h du matin.",
    category: "tod",
    rarity: "rare",
    xp: 250,
    isSecret: true,
    secretDescription: "Une heure bien mystérieuse pour écouter de la musique...",
    maxProgress: 1,
    check: (s) => (s.genreCounts["_tod_3am"] || 0) >= 1 ? 1 : 0,
  },
  {
    id: "tod3",
    name: "Aube",
    description: "Écouter de la musique au lever du soleil (entre 5h et 7h).",
    category: "tod",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 1,
    check: (s) => (s.genreCounts["_tod_sunrise"] || 0) >= 1 ? 1 : 0,
  },
  {
    id: "tod4",
    name: "Noctambule",
    description: "Écouter de la musique après 4h du matin (entre 4h00 et 4h59).",
    category: "tod",
    rarity: "uncommon",
    xp: 100,
    isSecret: true,
    secretDescription: "Vaincre le sommeil avec une bonne mélodie.",
    maxProgress: 1,
    check: (s) => (s.genreCounts["_tod_4am"] || 0) >= 1 ? 1 : 0,
  },

  {
    id: "dy1",
    name: "Hebdomadaire",
    description: "Écouter de la musique pendant 7 jours d'affilée.",
    category: "days",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 7,
    check: (s) => s.streakDays,
  },
  {
    id: "dy2",
    name: "Mensuel",
    description: "Écouter de la musique pendant 30 jours au total.",
    category: "days",
    rarity: "rare",
    xp: 250,
    isSecret: false,
    maxProgress: 30,
    check: (s) => s.uniqueTracks.length >= 30 ? 30 : s.uniqueTracks.length,
  },
  {
    id: "dy3",
    name: "Centenaire Temporel",
    description: "Écouter de la musique pendant 100 jours au total.",
    category: "days",
    rarity: "epic",
    xp: 500,
    isSecret: false,
    maxProgress: 100,
    check: (s) => s.uniqueTracks.length >= 100 ? 100 : s.uniqueTracks.length,
  },
  {
    id: "dy4",
    name: "Anniversaire",
    description: "Écouter de la musique pendant 365 jours au total.",
    category: "days",
    rarity: "legendary",
    xp: 1000,
    isSecret: false,
    maxProgress: 365,
    check: (s) => s.uniqueTracks.length >= 365 ? 365 : s.uniqueTracks.length,
  },

  {
    id: "sg1",
    name: "Jazzman",
    description: "Écouter 20 morceaux de Jazz.",
    category: "specific_genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => countGenreMatches(s.genreCounts, ["jazz"]),
  },
  {
    id: "sg2",
    name: "Rappeur",
    description: "Écouter 20 morceaux de Rap ou Hip-hop.",
    category: "specific_genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => countGenreMatches(s.genreCounts, ["rap", "hip hop", "hip-hop"]),
  },
  {
    id: "sg3",
    name: "Rocker",
    description: "Écouter 20 morceaux de Rock.",
    category: "specific_genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => countGenreMatches(s.genreCounts, ["rock", "grunge", "punk"]),
  },
  {
    id: "sg4",
    name: "Metalhead",
    description: "Écouter 20 morceaux de Metal.",
    category: "specific_genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => countGenreMatches(s.genreCounts, ["metal", "deathcore", "metalcore"]),
  },
  {
    id: "sg5",
    name: "Mélomane Classique",
    description: "Écouter 20 morceaux de Musique Classique.",
    category: "specific_genres",
    rarity: "uncommon",
    xp: 100,
    isSecret: false,
    maxProgress: 20,
    check: (s) => countGenreMatches(s.genreCounts, ["classical", "orchestral", "baroque", "opera"]),
  },
];

export function getLocalizedAchievement(def: AchievementDefinition, lang: "fr" | "en") {
  if (lang !== "en") return def;
  const translation = ACHIEVEMENT_TRANSLATIONS[def.id];
  if (!translation) return def;
  return {
    ...def,
    name: translation.nameEn,
    description: translation.descEn,
    secretDescription: translation.secretDescEn || def.secretDescription,
  };
}

export const ACHIEVEMENT_TRANSLATIONS: Record<string, { nameEn: string; descEn: string; secretDescEn?: string }> = {
  g1: { nameEn: "First Step", descEn: "Listen to one song." },
  g2: { nameEn: "Centenary", descEn: "Listen to 100 songs." },
  g3: { nameEn: "Melomaniac", descEn: "Listen to 500 songs." },
  g4: { nameEn: "Passionate", descEn: "Listen to 1,000 songs." },
  g5: { nameEn: "Music Legend", descEn: "Listen to 10,000 songs." },
  t1: { nameEn: "Initiated Listener", descEn: "Listen to 1 hour of music." },
  t2: { nameEn: "Frequent Flyer", descEn: "Listen to 10 hours of music." },
  t3: { nameEn: "Regular", descEn: "Listen to 100 hours of music." },
  t4: { nameEn: "Melophile", descEn: "Listen to 500 hours of music." },
  t5: { nameEn: "Venerable", descEn: "Listen to 1,000 hours of music." },
  t6: { nameEn: "Listening Deity", descEn: "Listen to 5,000 hours of music." },
  d1: { nameEn: "Beginner Explorer", descEn: "Listen to 10 different artists." },
  d2: { nameEn: "Talent Scout", descEn: "Listen to 100 different artists." },
  d3: { nameEn: "Musical Cartographer", descEn: "Listen to 500 different artists." },
  d4: { nameEn: "Living Encyclopedia", descEn: "Listen to 1,000 different artists." },
  al1: { nameEn: "First Spin", descEn: "Finish listening to 1 album." },
  al2: { nameEn: "Collector", descEn: "Finish listening to 10 albums." },
  al3: { nameEn: "Archivist", descEn: "Finish listening to 50 albums." },
  al4: { nameEn: "Museum Curator", descEn: "Finish listening to 100 albums." },
  p1: { nameEn: "Budding Creator", descEn: "Create 1 playlist." },
  p2: { nameEn: "Art Director", descEn: "Create 10 playlists." },
  p3: { nameEn: "Playlist Tycoon", descEn: "Create 50 playlists." },
  lk1: { nameEn: "Favorite", descEn: "Add 100 tracks to your Liked Songs." },
  lk2: { nameEn: "Golden Collection", descEn: "Add 500 tracks to your Liked Songs." },
  lk3: { nameEn: "Royal Library", descEn: "Add 1,000 tracks to your Liked Songs." },
  gn1: { nameEn: "Open Minded", descEn: "Discover 10 music genres." },
  gn2: { nameEn: "Musical Polyglot", descEn: "Discover 20 music genres." },
  gn3: { nameEn: "Chameleon", descEn: "Discover 50 music genres." },
  gn4: { nameEn: "Universal", descEn: "Discover 100 music genres." },
  n1: { nameEn: "Scout", descEn: "Listen to 100 new songs." },
  n2: { nameEn: "Pioneer", descEn: "Listen to 500 new songs." },
  o1: { nameEn: "Archaeologist", descEn: "Listen to 100 songs released before 1990." },
  lg1: { nameEn: "Marathoner", descEn: "Listen to 50 tracks over 8 minutes." },
  sh1: { nameEn: "Musical Snack", descEn: "Listen to 100 tracks under 2 minutes." },
  m1: { nameEn: "Tireless", descEn: "Listen to 5 hours of music without pause." },
  m2: { nameEn: "Survivor", descEn: "Listen to 10 hours of music without pause." },
  tod1: { nameEn: "Insomniac", descEn: "Listen to music at midnight (between 12:00 AM and 12:59 AM).", secretDescEn: "Listen to music in the middle of the night." },
  tod2: { nameEn: "Night Creature", descEn: "Listen to music at 3:00 AM.", secretDescEn: "A very mysterious hour to listen to music..." },
  tod3: { nameEn: "Dawn", descEn: "Listen to music at sunrise (between 5:00 AM and 7:00 AM)." },
  tod4: { nameEn: "Night Owl", descEn: "Listen to music after 4:00 AM (between 4:00 AM and 4:59 AM).", secretDescEn: "Defeat sleep with a good melody." },
  dy1: { nameEn: "Weekly", descEn: "Listen to music for 7 days in a row." },
  dy2: { nameEn: "Monthly", descEn: "Listen to music for 30 days in total." },
  dy3: { nameEn: "Temporal Centenary", descEn: "Listen to music for 100 days in total." },
  dy4: { nameEn: "Anniversary", descEn: "Listen to music for 365 days in total." },
  sg1: { nameEn: "Jazzman", descEn: "Listen to 20 Jazz tracks." },
  sg2: { nameEn: "Rapper", descEn: "Listen to 20 Rap or Hip-Hop tracks." },
  sg3: { nameEn: "Rocker", descEn: "Listen to 20 Rock tracks." },
  sg4: { nameEn: "Metalhead", descEn: "Listen to 20 Metal tracks." },
  sg5: { nameEn: "Classical Listener", descEn: "Listen to 20 Classical tracks." }
};
